title: Projects
description: Cybersecurity Projects | Network Security | Pentesting | CTF Writeups
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

collections:
  projects:
    output: true
    permalink: /projects/:name/
