title: Anna M
description: Cybersecurity Projects | Binary Exploitation | Network Forensics
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
include:
  - css/custom.css


collections:
  projects:
    output: true
    permalink: /projects/:name/
