title: Anna M
description: Cybersecurity Projects | Binary Exploitation | Network Forensics
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
include:
  - css/styles.css
  defaults:
  -
    scope:
      path: ""
    values:
      head: head-custom



collections:
  projects:
    output: true
    permalink: /projects/:name/
